image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
- hut
- hugo
environment:
  site: huma.id
tasks:
- package: |
    cd $site
    hugo
    tar -cvz ./public/ > ../site.tar.gz
- upload: |
    hut pages publish -d $site site.tar.gz
