baseURL = "https://humaidq.ae/"
languageCode = "en-gb"
title = "Humaid AlQassimi's Website"
copyright = "The content of this site is CC BY-SA 4.0. The code of this site is BSD 2-Clause."
preserveTaxonomyNames = true
pygmentsUseClasses = true
pygmentsCodeFences = true
disableHugoGeneratorInject = true
[Params]
	name = "Humaid AlQassimi"
	images = ["img/me-2020.jpg"]
[minify]
	minifyOutput = true

[taxonomies]
    location = "location"

[markup.tableOfContents]
	startLevel = 3
	endLevel = 4
[markup.goldmark.renderer]
	unsafe = true
