baseURL = "https://humaidq.ae/"
languageCode = "en-us"
title = "Humaid AlQassimi's Website"
theme = "humaidq-theme"
preserveTaxonomyNames = true
pygmentsUseClasses = true
pygmentsCodeFences = true
enableGitInfo = true
disableHugoGeneratorInject = true
#canonifyURLs = true
[Params]
	images = ["img/me.jpg"]
	ISO8601 = "2006-01-02T15:04:05GMT"
  	profilePicEnabled = true

sectionPagesMenu = "main"

paginate = 5
paginatePath = ""

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "now"
    name = "Now"
    url = "/now/"
    weight = 11
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 20
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 30
  [[menu.main]]
    identifier = "gallery"
    name = "Gallery"
    url = "/gallery/"
    weight = 40
  [[menu.main]]
    identifier = "xmath-pp"
    url = "/xmath-pp/"
    weight = -100
  [[menu.main]]
    identifier = "contribution"
    url = "/contribution/"
    weight = -100

[taxonomies]
#    license = "license"
    location = "location"
#    language = "language"

[blackfriday]
  hrefTargetBlank = true
  noreferrerLinks = true

[markup]
	[markup.tableOfContents]
		startLevel = 3
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
			xHTML = true
