baseURL = "https://huma.id/"
languageCode = "en-gb"
title = "Humaid AlQassimi's Website"
copyright = "The content of this site is CC BY-SA 4.0. The code of this site is BSD 2-Clause."
preserveTaxonomyNames = true
pygmentsUseClasses = true
pygmentsCodeFences = true
disableHugoGeneratorInject = true
enableGitInfo = true
[Params]
	name = "Humaid AlQassimi"
	image = "avatar.webp"
	imagealt = "A picture of Humaid smiling, not while looking at the camera. Possibly in a discussion with people off-screen."
[minify]
	minifyOutput = true

[taxonomies]
    location = "location"

[markup.tableOfContents]
	startLevel = 3
	endLevel = 5
[markup.goldmark.renderer]
	unsafe = true
